FROM debian:stretch
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update -qq && \
	apt-get install --no-install-recommends -y \
		build-essential \
		doxygen \
		graphviz \
		cmake \
		libgl1-mesa-dev \
		libboost-all-dev \
		libepoxy-dev \
		libglm-dev \
		libsoil-dev \
		pkg-config && \
	apt-get clean

# vim: ft=dockerfile
