FROM ubuntu:xenial
MAINTAINER Vincent Tavernier <vince.tavernier@gmail.com>
RUN apt-get update -qq && \
	apt-get install -y build-essential ca-certificates cmake \
	debhelper devscripts doxygen dpkg-dev git graphviz \
	libboost-all-dev libc6-dev libglew-dev libglfw3-dev \
	libpng-dev libsoil-dev libstdc++6
VOLUME /app
WORKDIR /app/libshadertoy-0.0.1
ENV SHADERTOY_ENTRYPOINT ubuntu
ENTRYPOINT ["/app/libshadertoy-0.0.1/entrypoint.sh"]
