FROM amd64/debian:stretch
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update -qq && \
	apt-get install --no-install-recommends -y \
		git \
		ca-certificates \
		curl \
		build-essential \
		debhelper \
		libboost-filesystem-dev \
		libc6-dev \
		libstdc++-6-dev \
		libsoil-dev \
		libjpeg-dev \
		libepoxy-dev \
		libglm-dev \
		libopenexr-dev \
		doxygen \
		doxygen-latex \
		graphviz \
		pkg-config \
		cmake && \
	apt-get clean

# vim: ft=dockerfile
