var namespaceshadertoy =
[
    [ "buffers", "namespaceshadertoy_1_1buffers.html", "namespaceshadertoy_1_1buffers" ],
    [ "compiler", "namespaceshadertoy_1_1compiler.html", "namespaceshadertoy_1_1compiler" ],
    [ "geometry", "namespaceshadertoy_1_1geometry.html", "namespaceshadertoy_1_1geometry" ],
    [ "gl", "namespaceshadertoy_1_1gl.html", "namespaceshadertoy_1_1gl" ],
    [ "inputs", "namespaceshadertoy_1_1inputs.html", "namespaceshadertoy_1_1inputs" ],
    [ "members", "namespaceshadertoy_1_1members.html", "namespaceshadertoy_1_1members" ],
    [ "utils", "namespaceshadertoy_1_1utils.html", "namespaceshadertoy_1_1utils" ],
    [ "basic_size", "structshadertoy_1_1basic__size.html", "structshadertoy_1_1basic__size" ],
    [ "draw_state", "classshadertoy_1_1draw__state.html", "classshadertoy_1_1draw__state" ],
    [ "explicit_size", "classshadertoy_1_1explicit__size.html", "classshadertoy_1_1explicit__size" ],
    [ "explicit_size_ref", "classshadertoy_1_1explicit__size__ref.html", "classshadertoy_1_1explicit__size__ref" ],
    [ "getter_size_ref", "classshadertoy_1_1getter__size__ref.html", "classshadertoy_1_1getter__size__ref" ],
    [ "input_resource", "structshadertoy_1_1input__resource.html", "structshadertoy_1_1input__resource" ],
    [ "io_resource", "classshadertoy_1_1io__resource.html", "classshadertoy_1_1io__resource" ],
    [ "output_buffer_spec", "structshadertoy_1_1output__buffer__spec.html", "structshadertoy_1_1output__buffer__spec" ],
    [ "output_resource", "structshadertoy_1_1output__resource.html", "structshadertoy_1_1output__resource" ],
    [ "program_input", "classshadertoy_1_1program__input.html", "classshadertoy_1_1program__input" ],
    [ "program_interface", "classshadertoy_1_1program__interface.html", "classshadertoy_1_1program__interface" ],
    [ "program_resource", "structshadertoy_1_1program__resource.html", "structshadertoy_1_1program__resource" ],
    [ "render_context", "classshadertoy_1_1render__context.html", "classshadertoy_1_1render__context" ],
    [ "resource_interface", "classshadertoy_1_1resource__interface.html", "classshadertoy_1_1resource__interface" ],
    [ "shader_compiler", "classshadertoy_1_1shader__compiler.html", null ],
    [ "shadertoy_error", "classshadertoy_1_1shadertoy__error.html", "classshadertoy_1_1shadertoy__error" ],
    [ "size_ref_interface", "classshadertoy_1_1size__ref__interface.html", "classshadertoy_1_1size__ref__interface" ],
    [ "size_ref_interface_ref", "classshadertoy_1_1size__ref__interface__ref.html", "classshadertoy_1_1size__ref__interface__ref" ],
    [ "swap_chain", "classshadertoy_1_1swap__chain.html", "classshadertoy_1_1swap__chain" ],
    [ "uniform_resource", "structshadertoy_1_1uniform__resource.html", "structshadertoy_1_1uniform__resource" ]
];